### ISSUE TITLE
Please add a license file and a screen shot

### ISSUE THREAD

**Issue by unixorn** [kalsowerus/kalsowerus.zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by kalsowerus** [comment]
I added a license file and updated the README with additional information as well as a screenshot.

**Comment by unixorn** [comment]
One last thing - could you rename it to something less generic than zsh-theme? Sorry, I should have included that when I created the issue.
